### PR TITLE
Fix l10n (localisation) of installation message etc.

### LINKED ISSUE #111: Installation message is not localized
## Bug description

First installation message should be localized. This s the first thing new users see, so it's really not good they don't see it in their locale.

## Steps to reproduce

1. Install extension.

### Actual behavior

Message is always in English.

### Expected behavior

Shown in your local language.

## System

not relevant

## Possible solution

Internationalize and localize (if you happen to speak German e.g.). the code here:
https://github.com/rugk/unicodify/blob/d4894d3d522293dd265c4570d10b75d0d6468b19/src/background/modules/InstallUpgrade.js#L39-L63

Cf. also https://github.com/rugk/unicodify/issues/101

### PR DESCRIPTION
**Pull request by rugk**
Based on https://github.com/rugk/unicodify/pull/112

grafik

grafik

Fixes https://github.com/rugk/unicodify/issues/111

/cc @Tabbie05

### CODE REVIEW

File: src/background/modules/InstallUpgrade.js [hunk 1]
```diff
@@ -35,36 +32,52 @@ function handleInstalled(details) {
...
+                });
+            }
+            break;
     }
 }
 
 browser.runtime.onInstalled.addListener(handleInstalled);
 
-// Previous exit survey: https://forms.gle/P8ThPXAvbGEkshYDA
+// Previous exit survey
```
Comment (tdulcet) [inline src/background/modules/InstallUpgrade.js]: The link to our previous exit survey is useful for reference and to know that it was migrated from Google Forms to CryptPad.

File: package-lock.json
Comment (tdulcet) [inline package-lock.json:1]: Is this file necessary, as this add-on does not use NPM and has no NPM dependencies.

**Review by tdulcet — COMMENTED** [review]
Thanks for testing and fixing this! There are just a couple of changes from #112 I am not sure were meant to be included.

File: src/background/modules/InstallUpgrade.js (hunk 1 above)
Comment (rugk) [reply src/background/modules/InstallUpgrade.js]: Hmm but only for historical relevance. The new one has the same questions so I see no reason to keep it.

And if one wants the history one can just check the git history, can't they?

File: package-lock.json
Comment (rugk) [reply package-lock.json:1]: Hmm in some other PR it das added.

File: src/background/modules/InstallUpgrade.js (hunk 1 above)
Comment (tdulcet) [reply src/background/modules/InstallUpgrade.js]: Looking at the git history is only helpful if one already knows that there is a previous exit survey to look for.

Anyway, if you are going to remove this link, you should remove the entire comment, as otherwise it would be confusing.

File: package-lock.json
Comment (tdulcet) [reply package-lock.json:1]: The file was added in #112 and then copied to this PR. Considering that this add-on does not use NPM and has no direct NPM dependencies (there is no `package.json` file), it seems unnecessary.

File: src/background/modules/InstallUpgrade.js (hunk 1 above)
Comment (rugk) [reply src/background/modules/InstallUpgrade.js]: Oh yeah obviously:
```suggestion
```

Comment (rugk) [reply src/background/modules/InstallUpgrade.js]: my brain kinda skipped the word "previous"

**Review by tdulcet — APPROVED** [review]
